name: protocol_handler_plus_example
description: Demonstrates how to use the protocol_handler_plus plugin.
repository: https://github.com/stan-at-work/protocol_handler_plus
issue_tracker: https://github.com/stan-at-work/protocol_handler_plus/issues
publish_to: "none"
topics: 
  - deeplinking
  - protocol
  

environment:
  sdk: ">=3.10.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  protocol_handler_plus:
    path: ../

  bot_toast: ^4.1.3
  preference_list: ^0.0.1
  uni_platform: ^0.1.3
  window_manager: ^0.5.2

dependency_overrides:
  protocol_handler_plus_android:
    path: ../../protocol_handler_plus_android
  protocol_handler_plus_ios:
    path: ../../protocol_handler_plus_ios
  protocol_handler_plus_macos:
    path: ../../protocol_handler_plus_macos
  protocol_handler_plus_platform_interface:
    path: ../../protocol_handler_plus_platform_interface
  protocol_handler_plus_windows:
    path: ../../protocol_handler_plus_windows

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
