name: protocol_handler_plus_platform_interface
description: A common platform interface for the protocol_handler_plus plugin.
version: 2.0.0
homepage: https://github.com/stan-at-work/protocol_handler_plus/blob/main/packages/protocol_handler_plus_platform_interface
repository: https://github.com/stan-at-work/protocol_handler_plus/blob/main/packages/protocol_handler_plus_platform_interface
issue_tracker: https://github.com/stan-at-work/protocol_handler_plus/issues
topics: 
  - deeplinking
  - protocol

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
