name: protocol_handler_plus_android
description: Android implementation of the protocol_handler_plus plugin.
version: 2.0.0
repository: https://github.com/stan-at-work/protocol_handler_plus/tree/main/packages/protocol_handler_plus_android
homepage: https://github.com/stan-at-work/protocol_handler_plus/tree/main/packages/protocol_handler_plus_android
issue_tracker: https://github.com/stan-at-work/protocol_handler_plus/issues
topics: 
  - deeplinking
  - protocol

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.16.0"
  
# publish_to: none
# dependency_overrides:
#   protocol_handler_plus_platform_interface:
#     path: ../protocol_handler_plus_platform_interface

dependencies:
  flutter:
    sdk: flutter
  protocol_handler_plus_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    implements: protocol_handler_plus
    platforms:
      android:
        package: dev.stan_at_work.plugins.protocol_handler_plus
        pluginClass: ProtocolHandlerPlusAndroidPlugin
